markdown: redcarpet
# Site settings
title: Pi Day - La tournée de Pi
email: contact@piday.fr
description: > # this means to ignore newlines until "baseurl:"
  Site officiel de la tournée de Pi. Retrouvez toutes les informations utiles sur cette tournée musicale mathématique totalement transcendante !
baseurl: ""
#url: "http://www.piday.fr" # the base hostname & protocol for your site

#gems:
#  - jekyll-redirect-from
